n

diff --git a/.github/workflows/kazikrypto.yml b/.github/workflows/kazikrypto.yml
--- a/.github/workflows/kazikrypto.yml
+++ b/.github/workflows/kazikrypto.yml
@@ -3,31 +3,31 @@ on: push
 
 jobs:
 
-  coverage:
-    runs-on: ubuntu-latest
-    steps: 
-    - uses: actions/checkout@v3
-    - name: Use Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: "16.x"
-    - name: Install Truffle and solidity coverage 
+  # coverage:
+  #   runs-on: ubuntu-latest
+  #   steps: 
+  #   - uses: actions/checkout@v3
+  #   - name: Use Node.js
+  #     uses: actions/setup-node@v3
+  #     with:
+  #       node-version: "16.x"
+  #   - name: Install Truffle and solidity coverage 
     
-      run: npm install -g truffle solidity-coverage@0.7.22
-    - name: install packages
-      run: |
-        cd contract 
-        npm install
-       # npm install --save-dev solidity-coverage
-    - name: Check Test Coverage
-      id: coverage
-      run: |
-        cd contract
-        truffle run coverage 
+  #     run: npm install -g truffle solidity-coverage@0.7.22
+  #   - name: install packages
+  #     run: |
+  #       cd contract 
+  #       npm install
+  #      # npm install --save-dev solidity-coverage
+  #   - name: Check Test Coverage
+  #     id: coverage
+  #     run: |
+  #       cd contract
+  #       truffle run coverage 
      
   test:
-    needs: coverage
-    if: ${{ success() }}
+    # needs: coverage
+  
 
     runs-on: ubuntu-latest
 
@@ -45,31 +45,30 @@ jobs:
         node-version: "16.x"
     - name: Install Truffle and solidity coverage 
     
-      run: npm install -g truffle solidity-coverage
+      run: npm install -g truffle solidity-coverage@0.7.22
     - name: install packages
       run: cd contract && npm install
 
     # - run: pwd
 
 
-    # - name: Check Test Coverage
-    #   # id: coverage
-    #   run: |
-    #     cd contract
-    #     truffle run coverage
-    #     coverage_pct=$(jq .total.lines.pct coverage/contracts/report.json)
+    - name: Check Test Coverage
+      # id: coverage
+      run: |
+        cd contract
+        truffle run coverage
+        coverage_pct=$(jq .total.lines.pct coverage/contracts/report.json)
     
-    #     if [ "$coverage_pct" -lt "100" ]; then
-    #       echo "::error ::Coverage of ${coverage_pct}% is below 100% target."
-    #       exit 1
-    #     fi
+        if [ "$coverage_pct" -lt "100" ]; then
+          echo "::error ::Coverage of ${coverage_pct}% is below 100% target."
+          exit 1
+        fi
         
-    #     echo "::set-output name=coverage::${coverage_pct}"
+        echo "::set-output name=coverage::${coverage_pct}"
     
-    # - name: Fail if coverage < 100%
-    # if:
-    #  steps.coverage.outputs.coverage < 100
-    #   run: exit 1
+    - name: Fail if coverage < 100%
+      if: steps.coverage.outputs.coverage < 100
+      run: exit 1
 
     - name: Run Tests
       run: cd contract && truffle test --network ganache
