update

diff --git a/.github/workflows/kazikrypto.yml b/.github/workflows/kazikrypto.yml
--- a/.github/workflows/kazikrypto.yml
+++ b/.github/workflows/kazikrypto.yml
@@ -45,7 +45,7 @@ jobs:
         node-version: "16.x"
     - name: Install Truffle and solidity coverage 
     
-      run: npm install -g truffle  solidity-coverage@0.8.2
+      run: npm install -g truffle  
     - name: install packages
       run: cd contract && npm install
 
@@ -66,28 +66,29 @@ jobs:
         
         echo "::set-output name=coverage::${coverage_pct}"
     
-    - name: Fail if coverage < 100%
-      if: steps.coverage.outputs.coverage < 100
-      run: exit 1
+    # - name: Fail if coverage < 100%
+    #   if: steps.coverage.outputs.coverage < 100
+    #   run: exit 1
+    # // "solidity-coverage": "^0.7.22"
 
     - name: Run Tests
       run: cd contract && truffle test --network ganache
 
-  merge:
+  # merge:
 
-        needs: test
-        if: ${{ success() }}
+  #       needs: test
+  #       if: ${{ success() }}
     
-        runs-on: ubuntu-latest
+  #       runs-on: ubuntu-latest
     
-        steps:
+  #       steps:
         
-        - uses: actions/checkout@v2
+  #       - uses: actions/checkout@v2
         
-        - name: Merge to main
-          uses: devmasx/merge-branch@v1.4.0
-          with:
-            token: ${{ secrets.ADMIN_TOKEN }}
-            type: now
-            label_name: 'auto-merged'
-            target_branch: main
+  #       - name: Merge to main
+  #         uses: devmasx/merge-branch@v1.4.0
+  #         with:
+  #           token: ${{ secrets.ADMIN_TOKEN }}
+  #           type: now
+  #           label_name: 'auto-merged'
+  #           target_branch: main
